import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { MovexProvider } from "movex-react";
import movexConfig from "../src/movex.config";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  // TODO: Make this not local host
  const endpointUrl = 'localhost:3333';
  return (
    <MovexProvider
      movexDefinition={movexConfig}
      endpointUrl={endpointUrl}
      onConnectionStatusChange={(state) => console.log( `Movex Status: ${state.status}`)}
    >
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        {children}
      </body>
    </html>
    </MovexProvider>
  );
}
